title: Albert Ionut Gugescu
logo: "images/cv3_wb.png"
description: |
  <br>
  Analytical and results-driven data scientist with experience in leveraging data analysis,
  statistical modeling, and machine learning techniques to drive business insights and optimize processes.
  Proficient in **Python**, **SQL**, **PL/SQL** and **Power BI** with hands-on experience in **data manipulation**,
  **visualization**, and **predictive modeling**.
  <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: G-ZCN55JN90J # your Google Analytics tracking ID here

include:
  - assets/css/custom.css
