title: Albert Ionut Gugescu # your name (or website title) here
#logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Highly motivated data scientist with a passion for extracting meaningful insights from complex datasets. Seeking an entry-level position to apply my abilities in a professional environment.
  <br> 
  <dl>
    <dt>Skills:</dt>
      <dd>Pandas and Numpy</dd>
      <dd>Matplotlib and Seaborn</dd>
      <dd>Scipy</dd>
      <dd>Scikit-learn</dd>
      <dd>Tensorflow</dd>
      <dd>Tableau</dd>
      <dd>SQL and PL/SQL</dd>
      <dd>Excel</dd>  
    </dl>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
