title: Albert Ionut Gugescu # your name (or website title) here
logo: "images/cv3_wb.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Highly motivated data scientist with a passion for extracting meaningful insights from complex datasets. Seeking an entry-level position to apply my abilities in a professional environment.
  <br> 
  <dl>
    <dt>Skills:</dt>
    <ul>
      <li>Pandas and Numpy</li>
      <li>Matplotlib, Seaborn and Tableau</li>
      <li>Scipy</li>
      <li>Tensorflow, Scikit-learn, XGbbost, LGBM, CatBoost</li>
      <li>SQL and PL/SQL</li>
      <li></li>  
    </ul>
    </dl>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
